INSERT INTO ALUNO(NAME, ACTIVE, PERIOD) VALUES ('Julia', true, 'Tarde');
INSERT INTO ALUNO(NAME, ACTIVE, PERIOD) VALUES ('Rafael', false, 'Noite');
INSERT INTO ALUNO(NAME, ACTIVE, PERIOD) VALUES ('Angelo', true, 'Manhã');